INSERT INTO NETWORK (NETWORK_ID,NAME,NETWORK_TYPE,MSG_NAME,MSG_EXT_CLASS_NAME,IS_MSG_XML,ZONE_ID,NAMESPACES,VALIDATE_XML,XSD_INFO,ENCODING,GMD_RETRIES,TRAN_SUMMARY_SQL,HISTORYLOG_VISIBLE,SAF_VISIBLE,TRANLOG_VISIBLE,MONITORINGLOG_VISIBLE,COMMANDPROCESSOR_VISIBLE) VALUES (74,'New Network to add','2','aadsfdsfdsaf','asdfdsafdsfsd','1',NULL,'asdfdsfdsfs',3,'adsfdsaf','adsfdsafdas',10,'',NULL,NULL,NULL,NULL,NULL)
UPDATE NETWORK SET NETWORK_ID=15 ,NAME='Etisalat' ,NETWORK_TYPE='External Network' ,MSG_NAME='SDES asfdsafsadfdsafdsafdsafds' ,MSG_EXT_CLASS_NAME='EBIZMessageExtension' ,IS_MSG_XML='1' ,ZONE_ID=0 ,NAMESPACES='asdfsdafads' ,VALIDATE_XML=2 ,XSD_INFO='adsfdsaf' ,ENCODING='adsfdsafdas' ,GMD_RETRIES=4 ,TRAN_SUMMARY_SQL='' ,HISTORYLOG_VISIBLE=0 ,SAF_VISIBLE=0 ,TRANLOG_VISIBLE=0 ,MONITORINGLOG_VISIBLE=0 ,COMMANDPROCESSOR_VISIBLE=0  WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
UPDATE NETWORK SET NETWORK_ID=74,NAME='New Network to add',NETWORK_TYPE='2',MSG_NAME='aadsfdsfdsaf',MSG_EXT_CLASS_NAME='asdfdsafdsfsd',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfdsfdsfs',VALIDATE_XML=3,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=10,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='' WHERE NETWORK_ID = 74 
UPDATE NETWORK SET NETWORK_ID=15,NAME='Etisalat',NETWORK_TYPE='External Network',MSG_NAME='SDES asfdsafsadfdsafdsafdsafds',MSG_EXT_CLASS_NAME='EBIZMessageExtension',IS_MSG_XML='1',ZONE_ID=NULL,NAMESPACES='asdfsdafads',VALIDATE_XML=2,XSD_INFO='adsfdsaf',ENCODING='adsfdsafdas',GMD_RETRIES=4,TRAN_SUMMARY_SQL='',HISTORYLOG_VISIBLE=NULL,SAF_VISIBLE=NULL,TRANLOG_VISIBLE=NULL,MONITORINGLOG_VISIBLE=NULL,COMMANDPROCESSOR_VISIBLE=NULL,TRAN_SUMMARY_DETAIL_SQL='INSERT INTO TRAN_SUMMARY_DETAIL_TEMP 
				(DETAIL_LOG_ID, DETAIL_RECEIVED_DATE, NETWORK_ID, RESPONSE_CODE, DIRTY_FLAG,
				DATE_LOCAL, TIME_LOCAL, 
				SETTLEMENT_DATE, STAN, RELATIONSHIP_NUM, TRAN_CODE, 
				MSG_TYPE, PAN, FROM_ACCOUNT_NUM, TO_ACCOUNT_NUM, 
				ACCEPTED_LOCATION, TERMINAL_ID ,TRAN_AMOUNT, 
				TRAN_CURRENCY, TRAN_BASE_AMOUNT, TRAN_BASE_CURRENCY, 
				ORIGINAL_DETAIL_LOG_ID, ORIGINAL_DETAIL_RECEIVE_TIME, 
				ORIGINAL_TRAN_LOG_ID, ORIGINAL_TRAN_RECEIVE_TIME, CHANNEL_ID,
				ACQ_INST_ID_CODE, TERMINAL_ENTITY_ID, CUSTOMER_ENTITY_ID, 
				DATE_CONVERSION, CARD_ACCEPTOR_ID, RETRIEVAL_REF_ID,
				AUTH_ID_RESPONSE, TRAN_FEES, MERCHANT_TYPE,
				COMMISSION_AMOUNT, COMMISSION_RATE, PROCCODE, 
				VISA_TRAN_AMOUNT, VISA_TRAN_CURRENCY, TRANSMISSION_DATE,IBFT_DATA,
				CREATED_BY, UPDATED_BY)
				SELECT LOG_ID, RECEIVE_TIME, NETWORK_ID, ERROR_CODE, CASE WHEN TRAN_SUMMARY_DETAIL = 1 AND DIRTY_FLAG = 1 THEN 1 ELSE 0 END,null,null,null,var32_04,null,var32_03,var32_02,null,null,null,null,null,var32_08,null,null,null,null,null,TRAN_LOG_ID, TRAN_RECEIVE_TIME, convert(varchar(2),NETWORK_ID),null,1,1,null,null,null,null,null,NULL,NULL,NULL,NULL,NULL,NULL,var32_22,NULL,'system','system' FROM TRANSACTION_LOG_DETAIL A, ADAPTER 
				B WHERE A.ADAPTER_ID = B.ADAPTER_ID AND 
				B.NETWORK_ID =15 AND (A.TRAN_SUMMARY_DETAIL = 0  OR (A.TRAN_SUMMARY_DETAIL = 1 AND A.DIRTY_FLAG = 1)) AND var32_03 IN (SELECT TRAN_CODE FROM TRANSACTION_CODE)' WHERE NETWORK_ID = 15 
